version: '3.8'

services:
  vehiclesFleetMonolith:
    image: vehiclesfleet
    build:
      context: .
      dockerfile: VehiclesFleet/Dockerfile
    ports:
      - "81:80"
      - "3005:443"
    depends_on:
      - database
  database:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: mHDyhpoc4336HXuF0GYO
      ACCEPT_EULA: Y
      MSSQL_PID: Express
      MSSQL_TCP_PORT: 1433
      MSSQL_DATABASE: VehiclesFleet
      MSSQL_PASSWORD: mHDyhpoc4336HXuF0GYO
    ports:
      - "1433:1433"